### ISSUE TITLE
"Unzip error" during installation

### ISSUE THREAD

**Issue by mks-h** [wacko1805/magiskgapps.com#2]
When installing ZIP file (mine is based on `NikGapps-core-arm64-14-20240420-signed.zip`), Magisk fails with the following log:
```
- Copying zip to temp directory
! Unzip error
```

I can successfully open the ZIP file in the file manager or "unzip" command in Termux. I've also tried to re-archive all files with the "zip" command in Termux, with default compression as well as 0 compression — the error stays the same. Other modules install normally.

**Comment by mks-h** [comment]
Device: Google Pixel 3a
System: LineageOS 21 (Android 14)
Magisk: version 27.0 (27000)

**Comment by wacko1805** [comment]
Hello, have you tried flashing a different Magisk module to test the functionality of your Magisk app?

**Comment by mks-h** [comment]
Yes, I've tried installing [microG Installer Revived](https://github.com/nift4/microg_installer_revived) and it worked just fine.

**Comment by shuaixr** [comment]
I decompressed the converted magisk module, and the content of module.prop and uninstall.sh inside is "This is a test".
Is Magisk gapp maker a production version?
https://github.com/wacko1805/magiskgapps.com/blob/1afac815c96cff8f546030f3634a6929e1e1a2a3/maker/scripts/MindTheGApps.js#L34-L48
I checked the source code, and it seems there are no other special cases.

**Comment by mks-h** [comment]
Oh, my situation is the same. There are a lot of files with "This is a test" or "Hello World!" contents.

**Comment by wacko1805** [comment]
Has now been fixed. 
Pushed wrong repo and did not notice.

**Comment by Etsinshao** [comment]
"Unzip error" still exists
