### ISSUE TITLE
MindTheGapps- Unzip error

### ISSUE THREAD

**Issue by Draygon0** [wacko1805/magiskgapps.com#4]
Device: A13
Magisk Version: 27.0

After flashing MindTheGapps(arm) this error shows up in Magisk manager:

- Copying zip to temp directory
! Unzip error

**Comment by pcs3rd** [comment]
I'm also seeing this with Lineage 21 on a Pixel 5 regardless of Gapps variant.
Attempting to re-pack the zip doesn't work, either.

**Comment by FernFranc** [comment]
Any updates on this issue?

**Comment by wacko1805** [comment]
Sorry for late replies and for this isssue, is due to the script loading "META-INF" folder from the Opengapps module, instead of the MagiskGApps module. 

Fix is underway and will be released soon!

**Comment by wacko1805** [comment]
Fixed.
